export type TaskType = 'agent' | 'human';

export type TaskExecutor = 'auto' | 'api' | 'subscription';

export type TaskStatus =
  | 'backlog'
  | 'sprint'
  | 'building_context'
  | 'executing'
  | 'blocked'
  | 'completed'
  | 'archived';

export type BlockedKind = 'dependency' | 'missing_resource' | 'human_question' | 'error';

export interface BlockedInfo {
  kind: BlockedKind;
  detail: string;
  /** ids of unmet dependency tasks, or names of missing resources */
  refs: string[];
}

export type UpdateKind =
  | 'status'
  | 'context'
  | 'info'
  | 'problem'
  | 'question'
  | 'answer'
  | 'output';

export interface TaskUpdate {
  id: string;
  ts: string;
  kind: UpdateKind;
  /** who produced this update: 'agent', 'system', or a user's display name */
  actor: string;
  text: string;
}

export interface TaskAttachment {
  /** filename on disk under DATA_DIR/files/<taskId>/ */
  name: string;
  size: number;
  createdAt: string;
}

export interface Task {
  id: string;
  workspaceId: string;
  title: string;
  description: string;
  type: TaskType;
  status: TaskStatus;
  priority: 'low' | 'medium' | 'high';
  tags: string[];
  /** resource names (MCPs / credentials) this task needs before an agent can run it */
  requirements: string[];
  /** task ids that must be completed first */
  dependencies: string[];
  /** agent must confirm with a human before completing */
  askHuman: boolean;
  blocked: BlockedInfo | null;
  pendingQuestion: string | null;
  updates: TaskUpdate[];
  output: string | null;
  /** files generated by the agent (real deliverables: .pptx, .xlsx, .docx, .pdf) */
  attachments: TaskAttachment[];
  /** acceptance criteria — when set, the run is graded against it and revised until it passes */
  definitionOfDone: string | null;
  /** where this task executes: forced 'api' / 'subscription', or 'auto' (rules + Claude router) */
  executor: TaskExecutor;
  /** execution runs with token usage & cost (populated on reads) */
  runs?: TaskRun[];
  createdBy: string | null;
  createdAt: string;
  updatedAt: string;
  completedAt: string | null;
}

export interface TaskRun {
  id: string;
  taskId: string;
  model: string;
  simulated: boolean;
  inputTokens: number;
  outputTokens: number;
  cacheReadTokens: number;
  cacheWriteTokens: number;
  costUsd: number;
  durationMs: number;
  iterations: number;
  /** outcome grading result: 'passed' | 'max_iterations' | null (no rubric) */
  outcome: string | null;
  ts: string;
}

export type LessonKind = 'correction' | 'failure' | 'insight';

/** A distilled workspace memory — one generalizable fact the agents apply to future runs. */
export interface Lesson {
  id: string;
  workspaceId: string;
  text: string;
  kind: LessonKind;
  sourceTaskId: string | null;
  createdAt: string;
}

export type ResourceKind = 'mcp' | 'credential';

export interface Resource {
  id: string;
  workspaceId: string;
  name: string;
  kind: ResourceKind;
  /** MCP endpoint URL — set on kind 'mcp' resources to make them live connections */
  url: string | null;
  /** whether an encrypted secret value is stored in the vault for this resource */
  hasSecret: boolean;
  addedAt: string;
}

export interface User {
  id: string;
  email: string;
  name: string;
  createdAt: string;
}

export type MemberRole = 'owner' | 'member';

export interface Member {
  userId: string;
  email: string;
  name: string;
  role: MemberRole;
  addedAt: string;
}

export interface Workspace {
  id: string;
  name: string;
  role: MemberRole;
  createdAt: string;
}
