export type TaskType = 'agent' | 'human';

export type TaskStatus =
  | 'backlog'
  | 'sprint'
  | 'building_context'
  | 'executing'
  | 'blocked'
  | 'completed'
  | 'archived';

export type BlockedKind = 'dependency' | 'missing_resource' | 'human_question' | 'error';

export interface BlockedInfo {
  kind: BlockedKind;
  detail: string;
  /** ids of unmet dependency tasks, or names of missing resources */
  refs: string[];
}

export type UpdateKind =
  | 'status'
  | 'context'
  | 'info'
  | 'problem'
  | 'question'
  | 'answer'
  | 'output';

export interface TaskUpdate {
  id: string;
  ts: string;
  kind: UpdateKind;
  /** who produced this update: 'agent', 'system', or a user's display name */
  actor: string;
  text: string;
}

export interface TaskAttachment {
  /** filename on disk under DATA_DIR/files/<taskId>/ */
  name: string;
  size: number;
  createdAt: string;
}

export interface Task {
  id: string;
  workspaceId: string;
  title: string;
  description: string;
  type: TaskType;
  status: TaskStatus;
  priority: 'low' | 'medium' | 'high';
  tags: string[];
  /** resource names (MCPs / credentials) this task needs before an agent can run it */
  requirements: string[];
  /** task ids that must be completed first */
  dependencies: string[];
  /** agent must confirm with a human before completing */
  askHuman: boolean;
  blocked: BlockedInfo | null;
  pendingQuestion: string | null;
  updates: TaskUpdate[];
  output: string | null;
  /** files generated by the agent (real deliverables: .pptx, .xlsx, .docx, .pdf) */
  attachments: TaskAttachment[];
  createdBy: string | null;
  createdAt: string;
  updatedAt: string;
  completedAt: string | null;
}

export type ResourceKind = 'mcp' | 'credential';

export interface Resource {
  id: string;
  workspaceId: string;
  name: string;
  kind: ResourceKind;
  /** MCP endpoint URL — set on kind 'mcp' resources to make them live connections */
  url: string | null;
  /** whether an encrypted secret value is stored in the vault for this resource */
  hasSecret: boolean;
  addedAt: string;
}

export interface User {
  id: string;
  email: string;
  name: string;
  createdAt: string;
}

export type MemberRole = 'owner' | 'member';

export interface Member {
  userId: string;
  email: string;
  name: string;
  role: MemberRole;
  addedAt: string;
}

export interface Workspace {
  id: string;
  name: string;
  role: MemberRole;
  createdAt: string;
}
